Import necessary libraries

In [1]:
import numpy as np
import pandas as pd

# Function Application

There are three approaches of function applications: row- or column-wise, or element wise.
+ Table wise Function Application: `pipe()`
+ Row or Column Wise Function Application: `apply()`
+ Element wise Function Application: `applymap()`

## Table-wise Function Application

In [2]:
# For example, add a value 2 to all the elements in the DataFrame. Then,

def adder(ele1,ele2):
   return ele1+ele2

df = pd.DataFrame(np.random.randint(11,100,size=[5,3]),columns=['col1','col2','col3'])
print(df,'\n')

print(df.pipe(adder,2))

   col1  col2  col3
0    14    15    77
1    76    11    61
2    16    42    82
3    57    91    79
4    59    85    43

   col1  col2  col3
0    16    17    79
1    78    13    63
2    18    44    84
3    59    93    81
4    61    87    45

## Row or Column Wise Function Application
Arbitrary functions can be applied along the axes of a DataFrame or Panel using the `apply()` method
+ By default, the operation performs **column wise**

In [3]:
# Column-wise calculation

df = pd.DataFrame(np.random.randint(11,100,size=[4,3]),columns=['col1','col2','col3'])
print(df,'\n')
print(df.apply(np.mean))

   col1  col2  col3
0    68    21    41
1    98    68    99
2    29    54    46
3    21    90    20

col1    54.00
col2    58.25
col3    51.50
dtype: float64

In [4]:
# Row-wise calculation

df = pd.DataFrame(np.random.randint(11,100,size=[5,3]),columns=['col1','col2','col3'])
print(df,'\n')
print(df.apply(np.mean,axis=1))

   col1  col2  col3
0    84    63    42
1    16    12    97
2    70    16    97
3    88    67    86
4    76    12    23

0    63.000000
1    41.666667
2    61.000000
3    80.333333
4    37.000000
dtype: float64

In [5]:
df = pd.DataFrame(np.random.randint(10,100,size=[5,3]),columns=['col1','col2','col3'])
print(df,'\n')
print(df.apply(lambda x: x.max() - x.min()),'\n')
print(df.apply(lambda x: x.max() - x.min(), axis=1),'\n')

   col1  col2  col3
0    96    24    93
1    69    32    52
2    85    76    35
3    35    67    75
4    55    59    31

col1    61
col2    52
col3    62
dtype: int64

0    72
1    37
2    50
3    40
4    28
dtype: int64

## Element Wise Function Application
+ the methods `applymap()` on DataFrame and 
+ analogously `map()` on Series    
accept any Python function taking a single value and returning a single value.

In [6]:
df = pd.DataFrame(np.random.randint(10,100,size=[5,3]),columns=['col1','col2','col3'])
print(df,'\n')

df['col1'] = df['col1'].map(lambda x:x*100)
print(df)

   col1  col2  col3
0    76    57    73
1    90    19    82
2    81    61    58
3    65    25    41
4    75    88    76

   col1  col2  col3
0  7600    57    73
1  9000    19    82
2  8100    61    58
3  6500    25    41
4  7500    88    76

In [7]:
# My custom function
df = pd.DataFrame(np.random.randint(10,100,size=[5,3]),columns=['col1','col2','col3'])
print(df,'\n')

print(df.applymap(lambda x:x*100))

   col1  col2  col3
0    77    34    47
1    70    51    60
2    93    32    45
3    11    66    45
4    61    74    69

   col1  col2  col3
0  7700  3400  4700
1  7000  5100  6000
2  9300  3200  4500
3  1100  6600  4500
4  6100  7400  6900

# Reindexing
changes the row labels and column labels of a DataFrame

## Renaming 
The `rename()` method allows you to relabel an axis based on some mapping (a dict or Series) or an arbitrary function.

In [8]:
df1 = pd.DataFrame(np.random.randn(6,3),columns=['col1','col2','col3'])
print(df1,'\n')

df2 = df1.rename(columns={'col1' : 'c1', 'col2' : 'c2'},index = {0 : 'apple', 1 : 'banana', 2 : 'durian'})
print ("After renaming the rows and columns:")
print(df2)

       col1      col2      col3
0  1.228406 -0.518844 -0.342712
1  0.847668 -0.207017 -0.227197
2  0.320101 -0.604814 -0.426079
3 -1.658386 -1.371434 -1.148725
4 -0.243855  0.479014  0.767255
5 -0.272147  0.838986 -0.303606

After renaming the rows and columns:
              c1        c2      col3
apple   1.228406 -0.518844 -0.342712
banana  0.847668 -0.207017 -0.227197
durian  0.320101 -0.604814 -0.426079
3      -1.658386 -1.371434 -1.148725
4      -0.243855  0.479014  0.767255
5      -0.272147  0.838986 -0.303606

## Reindexing: `reindex()`
changes the *row labels* and *column labels* of a *DataFrame*. To reindex means to conform the data to match a given set of labels along a particular axis. 

This operator is actually extract the existing data with the give index and column-names:
+ Reorder the existing data to *match a new set of labels.*
+ Insert missing value (NA) markers in label locations where no data for the label existed.

In [9]:
N=20

df = pd.DataFrame({
   'A': pd.date_range(start='2016-01-01',periods=N,freq='D'),
   'x': np.linspace(0,stop=N-1,num=N),
   'y': np.random.rand(N),
   'C': np.random.choice(['Low','Medium','High'],N),
   'D': np.random.normal(100, 10, size=(N))
})

print(df,'\n')

#reindex the DataFrame
df_reindexed = df.reindex(index=[0,2,5], columns=['A', 'C', 'B'])

print(df_reindexed)

            A     x         y       C           D
0  2016-01-01   0.0  0.610175     Low   82.829680
1  2016-01-02   1.0  0.725553  Medium  104.374021
2  2016-01-03   2.0  0.069567  Medium  110.282588
3  2016-01-04   3.0  0.718116     Low   91.257733
4  2016-01-05   4.0  0.430943    High  101.989887
5  2016-01-06   5.0  0.073517     Low  104.564744
6  2016-01-07   6.0  0.598202  Medium  101.021197
7  2016-01-08   7.0  0.649460    High  102.759633
8  2016-01-09   8.0  0.106394    High  102.492506
9  2016-01-10   9.0  0.380257    High   74.878215
10 2016-01-11  10.0  0.735755  Medium   95.271799
11 2016-01-12  11.0  0.740391     Low   93.812293
12 2016-01-13  12.0  0.481372  Medium   95.561455
13 2016-01-14  13.0  0.201788  Medium   77.311744
14 2016-01-15  14.0  0.615961     Low  103.835463
15 2016-01-16  15.0  0.903836    High  107.809433
16 2016-01-17  16.0  0.534737     Low   93.435552
17 2016-01-18  17.0  0.245069     Low  103.584332
18 2016-01-19  18.0  0.673741     Low   67.129694
19 2016-01-20  19.0  0.188294  Medium   90.948631

           A       C   B
0 2016-01-01     Low NaN
2 2016-01-03  Medium NaN
5 2016-01-06     Low NaN

## Reindex to Align with Other Objects: `reindex_like()`

extract the intersect considering the intersect of indices and column lables

In [10]:
df1 = pd.DataFrame(np.random.randn(10,3),columns=['col1','col2','col3'])
df2 = pd.DataFrame(np.random.randn(7,3),columns=['col1','col2','col3'])

print(df1,'\n')
print(df2,'\n')

df1 = df1.reindex_like(df2)
print(df1)

       col1      col2      col3
0  0.788687  0.079010  1.751624
1 -0.362389  2.031756 -0.378911
2  0.835734  2.531059 -0.292166
3  0.047850  1.647656  2.918055
4  1.057731  0.429492  1.935178
5 -0.282774 -1.374173 -1.465555
6  0.280227 -0.793196 -0.438152
7  1.435444  0.257115 -1.607410
8 -0.264462  0.372539  0.042445
9  2.002346  0.935475 -0.076195

       col1      col2      col3
0 -0.737098  2.228199  0.560342
1 -0.209073 -1.506237 -0.733750
2  2.029905  0.345456  0.826845
3 -0.234903 -1.659624  1.330262
4 -0.512619  0.452624  0.264872
5 -0.373221 -0.086351  0.691210
6  0.316186 -1.168577  1.532486

       col1      col2      col3
0  0.788687  0.079010  1.751624
1 -0.362389  2.031756 -0.378911
2  0.835734  2.531059 -0.292166
3  0.047850  1.647656  2.918055
4  1.057731  0.429492  1.935178
5 -0.282774 -1.374173 -1.465555
6  0.280227 -0.793196 -0.438152

## Filling while ReIndexing:
`reindex()` takes an optional parameter method which is a filling method with values as follows −
+ pad/ffill − Fill values forward
+ bfill/backfill − Fill values backward
+ nearest − Fill from the nearest index values

In [11]:
df1 = pd.DataFrame(np.random.randint(10,100,size=[20,3]),columns=['col1','col2','col3'])
df2 = pd.DataFrame(np.random.randint(10,100,size=[5,3]),index=[0,2,3,8,9],columns=['col1','col2','col3'])

# Padding NAN's
print(df2.reindex_like(df1),'\n')

# Now Fill the NAN's with preceding Values
print ("Data Frame with Forward Fill:")
print(df2.reindex_like(df1,method='nearest'))

    col1  col2  col3
0   93.0  19.0  13.0
1    NaN   NaN   NaN
2   31.0  87.0  43.0
3   99.0  98.0  55.0
4    NaN   NaN   NaN
5    NaN   NaN   NaN
6    NaN   NaN   NaN
7    NaN   NaN   NaN
8   93.0  27.0  23.0
9   58.0  26.0  75.0
10   NaN   NaN   NaN
11   NaN   NaN   NaN
12   NaN   NaN   NaN
13   NaN   NaN   NaN
14   NaN   NaN   NaN
15   NaN   NaN   NaN
16   NaN   NaN   NaN
17   NaN   NaN   NaN
18   NaN   NaN   NaN
19   NaN   NaN   NaN

Data Frame with Forward Fill:
    col1  col2  col3
0     93    19    13
1     31    87    43
2     31    87    43
3     99    98    55
4     99    98    55
5     99    98    55
6     93    27    23
7     93    27    23
8     93    27    23
9     58    26    75
10    58    26    75
11    58    26    75
12    58    26    75
13    58    26    75
14    58    26    75
15    58    26    75
16    58    26    75
17    58    26    75
18    58    26    75
19    58    26    75

## Limits on Filling while Reindexing
The limit argument provides additional control over filling while reindexing. Limit specifies the maximum count of consecutive matches.

In [12]:
df1 = pd.DataFrame(np.random.randn(6,3),columns=['col1','col2','col3'])
df2 = pd.DataFrame(np.random.randn(2,3),columns=['col1','col2','col3'])

# Padding NAN's
print(df2.reindex_like(df1),'\n')

# Now Fill the NAN's with preceding Values
print("Data Frame with Forward Fill limiting to 1:")
print(df2.reindex_like(df1,method='ffill',limit=1),'\n')

       col1      col2      col3
0 -0.473361  0.021515 -0.088027
1  0.204369  0.423280  0.977983
2       NaN       NaN       NaN
3       NaN       NaN       NaN
4       NaN       NaN       NaN
5       NaN       NaN       NaN

Data Frame with Forward Fill limiting to 1:
       col1      col2      col3
0 -0.473361  0.021515 -0.088027
1  0.204369  0.423280  0.977983
2  0.204369  0.423280  0.977983
3       NaN       NaN       NaN
4       NaN       NaN       NaN
5       NaN       NaN       NaN

# Iteration

basic iteration (`for i in object`) produces −
+ Series − values
+ DataFrame − *column* labels, Panel − item labels

To iterate over the rows of the DataFrame, we can use the following functions −
+ `iteritems()` − to iterate over the *(key,value)* pairs of each *column*
+ `iterrows()` − iterate over the *rows* as (index,series) pairs
+ `itertuples()` − iterate over the *rows* as namedtuples

In [13]:
N=20
df = pd.DataFrame({
   'A': pd.date_range(start='2016-01-01',periods=N,freq='D'),
   'x': np.linspace(0,stop=N-1,num=N),
   'y': np.random.rand(N),
   'C': np.random.choice(['Low','Medium','High'],N).tolist(),
   'D': np.random.normal(100, 10, size=(N)).tolist()
   })

for col in df:
   print(col)

A
x
y
C
D

In [14]:
df = pd.DataFrame(np.random.randn(4,3),columns=['col1','col2','col3'])
for key,value in df.iteritems():
   print(key,value,'\n')

col1 0   -0.667776
1   -1.067020
2    1.837291
3   -0.398551
Name: col1, dtype: float64

col2 0   -0.496836
1    0.501528
2    0.401715
3   -1.359581
Name: col2, dtype: float64

col3 0    0.665743
1    1.621455
2   -0.931758
3   -1.201056
Name: col3, dtype: float64

In [15]:
df = pd.DataFrame(np.random.randn(4,3),columns = ['col1','col2','col3'])
for row_index,row in df.iterrows():
   print(row_index,row,'\n')

0 col1    1.230503
col2    0.890306
col3    0.614433
Name: 0, dtype: float64

1 col1    0.398550
col2    1.199188
col3    0.254442
Name: 1, dtype: float64

2 col1   -0.402358
col2   -1.531789
col3   -0.884733
Name: 2, dtype: float64

3 col1   -0.743195
col2    0.243879
col3   -0.902443
Name: 3, dtype: float64

In [16]:
df = pd.DataFrame(np.random.randn(4,3),columns = ['col1','col2','col3'])
for row in df.itertuples():
    print(row,'\n')

Pandas(Index=0, col1=-0.16387143100396886, col2=0.03392637464833854, col3=1.2522147323854815)

Pandas(Index=1, col1=0.23722746860496485, col2=-0.028455870386628584, col3=0.4390936902749303)

Pandas(Index=2, col1=0.13579975075119968, col2=-0.6946127225623349, col3=0.7394503147573049)

Pandas(Index=3, col1=0.8942534924941762, col2=1.6725947228584401, col3=0.978416369265719)

In [17]:
df = pd.DataFrame(np.random.randn(4,3),columns = ['col1','col2','col3'])

for index, row in df.iterrows():
   row['a'] = 10
print(df,'\n')

for index, row in df.iterrows():
   row['col1'] = 10
print(df)

       col1      col2      col3
0 -1.974193  0.280142  1.867391
1 -0.682530 -0.349768  0.844640
2 -0.343741 -0.422987 -0.445558
3 -0.771785  0.702183  1.121199

   col1      col2      col3
0  10.0  0.280142  1.867391
1  10.0 -0.349768  0.844640
2  10.0 -0.422987 -0.445558
3  10.0  0.702183  1.121199

# Sorting data
+ By label
+ By Actual Value

## By Label
Using the `sort_index()` method
+ Params:
> `axis=0` (By default), sorting is done on *row labels* in *ascending* order.   
> `axis=1`, sort column      
> `ascending = True or False`

In [18]:
unsorted_df = pd.DataFrame(np.random.randn(10,2),
                           index=[1,4,6,2,3,5,9,8,0,7],
                           columns = ['col2','col1'])

sorted_df=unsorted_df.sort_index()
print(sorted_df)

       col2      col1
0  0.087655  1.734912
1 -1.166004  0.945482
2 -1.399375 -0.560871
3  1.381548 -0.815624
4 -0.058032  0.119342
5  0.553962 -0.610068
6 -1.348926  1.046255
7  0.373710  0.496396
8 -0.296283  1.086998
9 -0.428491 -1.434730

### Order of Sorting
By passing the Boolean value to `ascending` parameter, the order of the sorting can be controlled.

In [19]:
unsorted_df = pd.DataFrame(np.random.randn(10,2),
                           index=np.random.permutation(np.arange(10)),
                           columns = ['col1','col2'])

sorted_df = unsorted_df.sort_index(ascending=False)
print(sorted_df)

       col1      col2
9  0.551211  0.017873
8 -1.654534 -0.547629
7 -0.565008 -0.224136
6 -0.199094  0.428103
5  0.166110 -1.255651
4 -0.505424 -0.787466
3 -1.850115 -0.206540
2 -0.905463 -1.895734
1  1.195148 -1.387171
0  1.146894 -1.304064

### Sort the Columns

By passing the axis argument with a value 0 or 1, the sorting can be done on the column labels. By default, axis=0, sort by row.

In [20]:
unsorted_df = pd.DataFrame(np.random.randn(10,2),
                           index=np.random.permutation(np.arange(10)),
                           columns = ['col2','col1'])
 
sorted_df=unsorted_df.sort_index(axis=1)
print(sorted_df)

       col1      col2
1 -0.819547  0.378281
9 -0.519194  0.307569
0  0.309686 -1.431013
2  3.898167 -0.721533
5 -0.077619  0.730883
8 -0.649037 -0.550952
6 -0.528964  0.480152
7  0.141318  0.545463
3  0.489908  0.102995
4  1.493722 -0.810923

## By Value
Like index sorting, `sort_values()` is the method for sorting by values. 

It accepts a `by` argument which will use the column name of the DataFrame

`sort_values()` provides a provision to choose the algorithm with param `kind` from `mergesort, heapsort and quicksort`. Mergesort is the only stable algorithm.

In [21]:
unsorted_df = pd.DataFrame({'col1':[2,1,1,1],'col2':[1,3,2,4]})
sorted_df = unsorted_df.sort_values(by='col1')

print(sorted_df)

   col1  col2
1     1     3
2     1     2
3     1     4
0     2     1

Observe, col1 values are sorted and the respective col2 value and row index will alter along with col1. Thus, they look unsorted.

'by' argument takes a list of column values.

In [22]:
unsorted_df = pd.DataFrame({'col1':[2,1,1,1],'col2':[1,3,2,4]})
sorted_df = unsorted_df.sort_values(by=['col1','col2'])

print(sorted_df)

   col1  col2
2     1     2
1     1     3
3     1     4
0     2     1

### Sorting Algorithm
`sort_values()` provides a provision to choose the algorithm from `mergesort, heapsort and quicksort`. Mergesort is the only stable algorithm.

In [23]:
unsorted_df = pd.DataFrame({'col1':[2,1,1,1],'col2':[1,3,2,4]})
sorted_df = unsorted_df.sort_values(by='col1' ,kind='mergesort')

print(sorted_df)

   col1  col2
1     1     3
2     1     2
3     1     4
0     2     1

# Working with Text Data
|Function|Description|
|----------|-----------|
|`lower()`|Converts strings in the Series/Index to lower case.|
|`upper()`|Converts strings in the Series/Index to upper case.|
|`len()`|Computes String length().|
|`strip()`|Helps strip whitespace(including newline) from each string in the Series/index from both the sides.|
|`split(' ')`|Splits each string with the given pattern.|
|`cat(sep=' ')`|Concatenates the series/index elements with given separator.|
|`get_dummies()`|Returns the DataFrame with One-Hot Encoded values.|
|`contains(pattern)`|Returns a Boolean value True for each element if the substring contains in the element, else False.|
|`replace(a,b)`|Replaces the value a with the value b.|
|`repeat(value)`|Repeats each element with specified number of times.|
|`count(pattern)`|Returns count of appearance of pattern in each element.|
|`startswith(pattern)`|Returns true if the element in the Series/Index starts with the pattern.|
|`endswith(pattern)`|Returns true if the element in the Series/Index ends with the pattern.|
|`find(pattern)`|Returns the first position of the first occurrence of the pattern.|
|`findall(pattern)`|Returns a list of all occurrence of the pattern.|
|`swapcase`|Swaps the case lower/upper.|
|`islower()`|Checks whether all characters in each string in the Series/Index in lower case or not. Returns Boolean|
|`isupper()`|Checks whether all characters in each string in the Series/Index in upper case or not. Returns Boolean.|
|`isnumeric()`|Checks whether all characters in each string in the Series/Index are numeric. Returns Boolean.|

In [24]:
# Set the maximum column in print option of Pandas
pd.set_option('max_columns', 20)
pd.set_option('max_colwidth', 200)

In [25]:
s = pd.DataFrame(pd.Series(['Tom', 'William Rick', 'John', 'Alber@t', np.nan, '1234','SteveSmith']),
                 columns=['s_value'])
print(s,'\n')
print(s['s_value'].str,'\n')

s['lower()'] = s['s_value'].str.lower()
s['upper()'] = s['s_value'].str.upper()
s['strip()'] = s['s_value'].str.strip()
s['split()'] = s['s_value'].str.split(' ')
s['len()'] = s['s_value'].str.len()
s['contains(' ')'] = s['s_value'].str.contains(' ')
s['replace()'] = s['s_value'].str.replace('@','$')
s['repeat(2)'] = s['s_value'].str.repeat(2)
s['count(\'m\')'] = s['s_value'].str.count('m')
s['startswith (\'T\')'] = s['s_value'].str.startswith ('T')
s['endswith (\'t\')'] = s['s_value'].str.endswith ('t')
s['find(\'e\')'] = s['s_value'].str.find('e')
s['findall(\'e\')'] = s['s_value'].str.findall('e')
s['swapcase()'] = s['s_value'].str.swapcase()
s['islower()'] = s['s_value'].str.islower()
s['isupper()'] = s['s_value'].str.isupper()
s['isnumeric()'] = s['s_value'].str.isnumeric()

print(s,'\n')

        s_value
0           Tom
1  William Rick
2          John
3       Alber@t
4           NaN
5          1234
6    SteveSmith

<pandas.core.strings.StringMethods object at 0x7fdd544b5be0>

        s_value       lower()       upper()       strip()          split()  \
0           Tom           tom           TOM           Tom            [Tom]
1  William Rick  william rick  WILLIAM RICK  William Rick  [William, Rick]
2          John          john          JOHN          John           [John]
3       Alber@t       alber@t       ALBER@T       Alber@t        [Alber@t]
4           NaN           NaN           NaN           NaN              NaN
5          1234          1234          1234          1234           [1234]
6    SteveSmith    stevesmith    STEVESMITH    SteveSmith     [SteveSmith]

   len() contains()     replace()                 repeat(2)  count('m')  \
0    3.0      False           Tom                    TomTom         1.0
1   12.0       True  William Rick  William RickWilliam Rick         1.0
2    4.0      False          John                  JohnJohn         0.0
3    7.0      False       Alber$t            Alber@tAlber@t         0.0
4    NaN        NaN           NaN                       NaN         NaN
5    4.0      False          1234                  12341234         0.0
6   10.0      False    SteveSmith      SteveSmithSteveSmith         1.0

  startswith ('T') endswith ('t')  find('e') findall('e')    swapcase()  \
0             True          False       -1.0           []           tOM
1            False          False       -1.0           []  wILLIAM rICK
2            False          False       -1.0           []          jOHN
3            False           True        3.0          [e]       aLBER@T
4              NaN            NaN        NaN          NaN           NaN
5            False          False       -1.0           []          1234
6            False          False        2.0       [e, e]    sTEVEsMITH

  islower() isupper() isnumeric()
0     False     False       False
1     False     False       False
2     False     False       False
3     False     False       False
4       NaN       NaN         NaN
5     False     False        True
6     False     False       False

In [26]:
s = pd.Series(['Tom ', ' William Rick', 'John', 'Alber@t'])
print(s.str.cat(sep='_'))

Tom _ William Rick_John_Alber@t

In [27]:
s = pd.Series(['Tom ', ' William Rick', 'John', 'Alber@t'])
print(s.str.get_dummies())

    William Rick  Alber@t  John  Tom
0              0        0     0     1
1              1        0     0     0
2              0        0     1     0
3              0        1     0     0